onEnableMessage: "KetheriumTools activated !"
onDisableMessage: "KetheriumTools desactivated !"
reloadMessage: "&aKetheriumTools reloaded !"

jobsAutojoin: true
jobsJoinMessage: "&aVous avez rejoins un métier !"