onEnableMessage:
  enable: true
  message: "KetheriumTools activated !"
onDisableMessage:
  enable: true
  message: "KetheriumTools desactivated !"
reloadMessage:
  enable: true
  message: "&cKetheriumTools reloaded !"